application: dhummel-1210
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /images-src
  static_dir: images-src

- url: /js
  static_dir: js

- url: /.*
  script: portfolio.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
